project:
  type: website

website:
  title: "Introduction to Version Control with Git & GitHub"
  navbar:
    left:
      - text: About
        href: index.qmd
      - text: "Pre-Workshop Materials"  
        menu:
         - pre-workshop/software-install.qmd
         - pre-workshop/assignment.qmd
      - text: "Slides"
        menu:
         - text: "Current Workshop - Spring 2025"
           href: slides/slides.qmd
         - text: "Previous Workshop - Fall 2023"
           href: slides/2024-05-03-bcstats-vc-git-hub.pptx
    right:     
      - icon: github
        href: https://github.com/bcgov/ds-intro-to-git
        text: GitHub
  sidebar:
    style: "docked"
    search: false
    contents:
      - course-outline.qmd
      - section: "Course Sections"
        contents:
          - materials/01-what-is-vc.qmd
          - materials/02-working-local.qmd
          - materials/03-remote-hosting.qmd
          - materials/04-bcgov-org.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: true
    number-depth: 3

editor: source

execute:
  freeze: auto

