---
title: "Bonnie's Scratch Pad"
author: "Bonnie Robert"
date: "2023-10-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Software Carpentry Likes

#### General Thoughts

- Like the learning objectives, don't love they way they are laid out.  I'd prefer seeing the question be a header and the objectives clearly outlined either above or below.
- teaching command line will take extra time as we'll need to teach that
- keep things simple: change directory, list directory contents, make and delete a directory then git commands.

#### Summary and Set Up

- A record of who made what changes when therefore we know who to ask if we have questions later on.  If needed we can revert to a previous version, much like the “undo” feature in an editor"
- Teams are not the only ones to benefit from version control: lone researchers can benefit immensely. 
- Anything that changes over time or needs to be shared can be stored in a version control system.

- We have installation instructions in a git repo somewhere - copy and paste to this directory?
- Ask ppl to show up ready-to-go with a git account, git installed, m2FA, RStudio (tbd), Git Bash?
- can we include the configuration as well?

- MacOS has a terminal running a bash or zsh shell for command line work.  Windows...Git Bash?

#### Episode 1. Automated Version Control
- not keen on the cartoon
- yes for the document flow diagrams

#### Episode 2. Setting Up Git
- am concerned this will lose ppl
- can we pass them a script before hand to work through?
- yes to touching on default branch naming (inclusive language)
- 

#### Episode 3. Creating a Repository
- mostly good, like the keypoints at the end
- making a subdirectory, 
- .gitgnore and .gitkeep
- they don't mention .gitkeep

#### Episode 4. Tracking Changes
- which editor?  will people be open to using nano? I'm guessing not, and the changes should be a
word doc or excel file.  we could mention R scripts here. ppl might find themselves in trouble when
when -m is omitted.
- yes to git log
- no to git diff (intermediate level)
- I don't think there will be time (in a 1/2 day workshop) to do the exercises 

#### Episode 5. Exploring History
- this is a deeper dive and could be rushing things to include.  If we include it, it need a rethink.  To me, this section feels like a bunch of information being tossed out, with no specific purpose.

#### Episode 6. Ignoring Things

#### Episode 7. Remotes in GitHub

#### Episode 8. Collaborating
- skip this section

#### Episode 9. Conflicts
- skip this section

#### Episode 10 - 13 
- collapse these into one unit where we discuss bcgov organization, licensing, code-sharing, PIA/STRA etc

#### Episode 14. Supplemental: Using Git from RStudio


