---
title: "Course Outline"
---

### Pre-Workshop Installation and Set Up

Learning Objective: Set up a GitHub account and install git (pre-workshop).\
Instructions: [Installation and Set-Up](./pre-workshop/software-install.html)\
Assignment: [Pre-Workshop Assignment](./pre-workshop/assignment.html)\

Topics/Learning Outcomes:

-   Download Git for Windows and bundled software (includes Git Bash) (PC only)
-   Download Git for Mac installer (Mac only)
-   Create a GitHub account with m2FA, PAT for https connection
-   Configure git
-   Pre-workshop assignment to show local configuration and connection to GitHub

Course Reference Material:

-   [SW Carpentry Episode 2. Setting Up Git](https://swcarpentry.github.io/git-novice/)
-   [bcgov-r-geo-workshop Lesson 1](https://github.com/bcgov/bcgov-r-geo-workshop/blob/master/20191105_Day_1_PM_Intro/lessons/01-setup.md)

### Section 1. Introductions and What is Version Control?

Learning Objective: Understand the value-add of using version control and the the basics of how automated version control systems work.

Topics:

-   How version control systems work
-   What is a repository?
-   What is the value-add of using version control in teams? individually?

Course Reference Material:

-   [SW Carpentry Episode 1. Automated Version Control](https://swcarpentry.github.io/git-novice/01-basics.html)

### Section 2. Working Locally with Git

Learning Objective: Use command-line git to track local file changes.

Topics:

-   Default branch naming (inclusive language)
-   What is Bash
-   Bash-specific commands: mkdir, rm -r, cd, ls
-   Git Bash commands: init, commit, add, status, log
-   Directory structure
-   Tracking changes made to a text doc
-   What to do when when -m is omitted.

Course Reference Material:

-   [SW Carpentry Episode 3. Creating a Repository (Local)](https://swcarpentry.github.io/git-novice/03-create.html)
-   [SW Carpentry Episode 4. Tracking Changes](https://swcarpentry.github.io/git-novice/04-changes.html)
-   [bcgov-r-geo-workshop Lesson 2](https://github.com/bcgov/bcgov-r-geo-workshop/blob/master/20191105_Day_1_PM_Intro/lessons/02-create.md)
-   [bcgov-r-geo-workshop Lesson 3](https://github.com/bcgov/bcgov-r-geo-workshop/blob/master/20191105_Day_1_PM_Intro/lessons/03-changes.md)
-   [bcgov-r-geo-workshop Lesson 5](https://github.com/bcgov/bcgov-r-geo-workshop/blob/master/20191105_Day_1_PM_Intro/lessons/05-ignore.md)

### Section 3. Remote Code Hosting and GitHub

Learning Objective: What are remote hosting platforms and why do we use them?

Topics:

-   More on secure authentication/login: username/password/2FA to sign in to account, PAT to authenticate
-   Git Bash commands: push, pull
-   Create a remote repository
-   Clone a remote repostitory
-   Push local changes to GitHub.
-   .gitgnore and subdirectories (we don't want ppl pushing data to GitHub)
-   .gitkeep (time permitting)

Course Reference Material:

-   [SW Carpentry Episode 6. Ignoring Things](https://swcarpentry.github.io/git-novice/06-ignore.html)
-   [SW Carpentry Episode 7. Remotes in GitHub](https://swcarpentry.github.io/git-novice/07-github.html)
-   [bcgov-r-geo-workshop Lesson 6](https://github.com/bcgov/bcgov-r-geo-workshop/blob/master/20191105_Day_1_PM_Intro/lessons/06-github.md)
-   [Github: Keeping your Account and Data Secure](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-authentication-to-github)

### Section 4. BCGov GitHub Organization

Learning Objective: Understand how the bcgov framework, policy and related tools help B.C. government employees share code on GitHub

Topics:

-   what is the `bcgov` organization framework
-   `bcgov` policy framework and licensing

Course Reference Material:

-   [SW Carpentry Episode 10. Open Science](https://swcarpentry.github.io/git-novice/10-open.html)
-   [SW Carpentry Episode 11. Licensing](https://swcarpentry.github.io/git-novice/11-licensing.html)
-   [SW Carpentry Episode 12. Citation](https://swcarpentry.github.io/git-novice/12-citation.html)
-   [SW Carpentry Episode 13. Hosting](https://swcarpentry.github.io/git-novice/13-hosting.html)

Further Links to `bcgov` Organization Resources:

-   [Content Approval Checklist](https://github.com/bcgov/BC-Policy-Framework-For-GitHub/blob/master/BC-Open-Source-Development-Employee-Guide/Content-Approval-Checklist.md)
-   [BC Gov Organizations in GitHub](https://docs.developer.gov.bc.ca/bc-government-organizations-in-github/)
-   [Policy Framework](https://github.com/bcgov/BC-Policy-Framework-For-GitHub/tree/master)
