---
title: "About The Workshop"
---

## Introduction To Version Control With Git and GitHub

This is a 1/2 day workshop introducing participants to version control using git and the popular code hosting platform, GitHub.

The goal of this workshop is to teach data professionals how to harness the power of version control by giving attendees a foundation in the fundamentals of version control with [git](https://git-scm.com).

GitHub is a widely-used platform for hosting and sharing code repositories, facilitating seamless collaboration among developers. Git, on the other hand, is a popular version control system that enables you to track changes in your code, collaborate with team members, and maintain a history of your project's development.

## Learning Outcomes

By the end of this course, you will have gained a fundamental understanding of version control, enabling you to:

-   Set up a GitHub account and install the software, git (see pre-workshop assignment)
-   Understand the value-add of using version control to manage software and code-based data science projects
-   Understand the basics of how automated version control systems work
-   Use git—popular command-line version control software—to track local file changes
-   Understand remote hosting platforms and why we use them
-   Connect to GitHub, create a remote repository and clone a local version to your PC
-   Be familiar with the [public BC Gov GitHub organization](https://github.com/bcgov) which has guidelines and requirements for hosting government developed open source repositories

You will also be able to follow a standard Git workflow to manage your work under existing version control using the following steps:

| Order          | Action           | Git Command                                   |
|----------------|------------------|-----------------------------------------------| 
| 1              | Update local     | `git pull origin main`                        |
| 2              | Make changes     | (Done in editor)                              |
| 3              | Stage changes    | `git add numbers.txt`                         |
| 4              | Commit changes   | `git commit -m "Add 100 to numbers.txt"`      |
| 5              | Update remote    | `git push origin main`                        |


The workshop content will follow best practices for version control such as writing descriptive commit messages, including a .gitignore file and tracking relevant project files.

## Who should take this course?

-   Anyone looking to solidify their understanding of version control
-   Anyone keen to learn what git or GitHub is (**no prior experience necessary!**)
-   Anyone wondering how version control can be used to manage and collaborate on software and code-based data science projects

## Workshop Schedule 

When: January 29, 2025, 9:00 - 12:30 

| Activity                                      | Start Time | End Time |
|-----------------------------------------------|------------|----------|
| **Session 1. What is version control?**       | 9:00       | 9:30     |
| **Session 2. Working locally with git**       | 9:30       | 10:30    |
| BREAK ☕                                      | 10:30      | 10:45    |
| **Session 3. Working remotely with GitHub**   | 10:45      | 11:45    |
| **Session 4. The BC Gov GitHub Organization** | 11:45      | 12:15    |
| Wrap Up & Questions                           | 12:15      | 12:30    |

## Pre-Course Work

**Important!**

Before the course begins, we ask that all attendees install Git and GitBash, and have a basic text editor installed, such as Wordpad, Notepad++, Visual Studio Code, or Sublime Text. Detailed installation instructions can be found at the [Installation Instructions and Set-Up](https://bcgov.github.io/ds-intro-to-git/pre-workshop/software-install.html) page. If you encounter any issues with the installation or setup, please reach out **prior** to the course start so we can ensure a smooth and productive workshop experience.